FROM --platform=$TARGETPLATFORM alpine:3.18.3

ARG TARGETOS
ARG TARGETARCH
#ARG TARGETPLATFORM

COPY app/boltdbwebeditor.$TARGETOS.$TARGETARCH /app/boltdbwebeditor
COPY app/static /app/static

EXPOSE 8080

ENTRYPOINT ["/app/boltdbwebeditor"]